const data = {
  products: [
    {
      name: 'Caleen Shaah',
      slug: 'caleen-shaah',
      category: 'orthdox',
      image: '/images/caleenta.jpeg',
      price: 150,
      brand: 'Amalina',
      rating: 4.6,
      numReviews: 7,
      countInStock: 100,
      description: 'A health caleen shaah',
    },
    {
      name: 'Caleen Shaah',
      slug: 'caleen-shaah',
      category: 'orthdox',
      image: '/images/caleenta.jpeg',
      price: 300,
      brand: 'Amalina',
      rating: 4.6,
      numReviews: 7,
      countInStock: 100,
      description: 'A health caleen shaah',
    },
    {
      name: 'Caleen Shaah',
      slug: 'caleen-shaah',
      category: 'orthdox',
      image: '/images/caleenta.jpeg',
      price: 400,
      brand: 'Amalina',
      rating: 4.6,
      numReviews: 7,
      countInStock: 100,
      description: 'A health caleen shaah',
    },
    {
      name: 'Caleen Shaah',
      slug: 'caleen-shaah',
      category: 'orthdox',
      image: '/images/caleenta.jpeg',
      price: 500,
      brand: 'Amalina',
      rating: 4.6,
      numReviews: 7,
      countInStock: 100,
      description: 'A health caleen shaah',
    },
    {
      name: 'Caleen Shaah',
      slug: 'caleen-shaah',
      category: 'orthdox',
      image: '/images/caleenta.jpeg',
      price: 600,
      brand: 'Amalina',
      rating: 4.6,
      numReviews: 7,
      countInStock: 100,
      description: 'A health caleen shaah',
    },
    {
      name: 'Caleen Shaah',
      slug: 'caleen-shaah',
      category: 'orthdox',
      image: '/images/caleenta.jpeg',
      price: 700,
      brand: 'Amalina',
      rating: 4.6,
      numReviews: 7,
      countInStock: 100,
      description: 'A health caleen shaah',
    },
  ],
};

export default data;
